# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date_time',
            field=models.DateTimeField(null=True, verbose_name='End Date Time'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date_time',
            field=models.DateTimeField(null=True, verbose_name='Start Date Time'),
        ),
    ]
