# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190830_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date Time'),
        ),
    ]
